"""Adicionando a tabela de disciplinas

Revision ID: 231fd7b9683f
Revises: 2fd834cc2602
Create Date: 2024-10-24 13:29:51.902959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231fd7b9683f'
down_revision = '2fd834cc2602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disciplinas')
    # ### end Alembic commands ###
